### ISSUE TITLE
Bản pdf không có bookmark list

### ISSUE THREAD

**Issue by phucnh** [vuhung/ddd-quickly-vietnamese#1]
Hi nhóm dịch!
Cám ơn các bạn đã dịch một tài liệu rất bổ ích.
### Vấn đề

Hiện mình đang đọc bản dịch của nhóm dưới dạng pdf và thấy rằng phần `Mục lục` chưa được link tới các phần tương ứng, cũng như tài liệu pdf chưa có bookmark. (hình dưới). Mình nghĩ với độc giả theo dõi bằng pdf có vẻ hơi bất tiện.

![image](https://cloud.githubusercontent.com/assets/1061090/12049062/03900f14-af26-11e5-8977-37cac95c9686.png)
### Cách giải quyết

Mình nghĩ bản pdf được generate từ bản `.doc`, vì vậy phương pháp đánh bookmark trực tiếp lên bản pdf có lẽ sẽ không được tối ưu.

Mình đề xuất hướng giải quyết như sau:
1. Download [Microsoft PDF Add-In](http://www.microsoft.com/en-us/download/details.aspx?id=9943)
2. Lưu bản `.doc` bằng Save As > PDF
3. Chọn options  →   Check `Create Bookmarks using headings` → OK
4. Chọn `Publish`

**Comment by vuhung** [comment]
Rất chuẩn.

Bạn update file doc, pdf, tạo pull request đi :)

**Comment by vuhung** [comment]
@phucnh :100:  Mình đã thử export lại PDF file, có bookmark, ổn chưa nhỉ?
(dùng Office 2010, save as, PDF, "bookmarks" option checked.

https://github.com/vuhung/ddd-quickly-vietnamese/commit/21da713f8d226d0810c3823c6eb88661b78fc862

**Comment by phucnh** [comment]
> Rất chuẩn.
> 
> Bạn update file doc, pdf, tạo pull request đi :)

@vuhung em vừa chạy ra ngoài bonenkai 1 lúc, về đã thấy anh sửa xong rồi. Em cám ơn anh.   :yum:

Em đã check bản mới, đã có bookmark đầy đủ, phần mục lục cũng đã link tới các phần tương ứng.
