### ISSUE TITLE
Từ "phương ngữ" (dialect) khá khó hiểu

### ISSUE THREAD

**Issue by phucnh** [vuhung/ddd-quickly-vietnamese#2]
Trong quá trình đọc, mình có gặp từ "phương ngữ" (có lẽ được dịch từ `Dialect`). Mình nghĩ đây là một từ ít được sử dụng trong tiếng Việt nên đối với bạn đọc có lẽ sẽ hơi khó hiểu.

Vì vậy mình tạo issue nhằm thảo luận về cách dịch từ `dialect` hoặc cách chú thích giúp độc giả dễ hiểu hơn.

**Comment by phucnh** [comment]
### Phương án 1

Tạo footnote để chú thích cho từ "phương ngữ" như hình dưới thì sao nhỉ?
![image](https://cloud.githubusercontent.com/assets/1061090/12052393/e6cca0f0-af51-11e5-9d45-58a6e30be2b2.png)

**Comment by vuhung** [comment]
@phucnh Vậy Phúc dùng chức năng suggest của Google docs, ghi thẳng vào file dịch trung gian đi. Khi nào ổn sẽ bóc ra .doc (và export ra PDF)

Xem: https://github.com/vuhung/ddd-quickly-vietnamese#b%E1%BA%A3n-d%E1%BB%8Bch-trung-gian-d%C3%A0nh-cho-collaboration

**Comment by vuhung** [comment]
added: https://github.com/vuhung/ddd-quickly-vietnamese/commit/e08111402f1990f0a92861b64c76a0f5d2db894f

Sẽ điều chỉnh thêm tiếp sau nhé.

**Comment by phucnh** [comment]
> Vậy Phúc dùng chức năng suggest của Google docs, ghi thẳng vào file dịch trung gian đi. Khi nào ổn sẽ bóc ra .doc (và export ra PDF)

DONE

**Comment by phucnh** [comment]
ồ, anh sửa luôn rồi à.

:+1:

**Comment by vuhung** [comment]
@phucnh Anh có từ điển tiếng Việt Vietlex 2015 trong tay đây ;)
